
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8669
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 此类由工具生成并可能分离数据实体类，要修改得注意!
// 创 建 人: SBW
// 创建日期: 2017/9/4 15:22:18
// 
namespace LGD.Entity
{
    using  System;
    using  System.Collections.Generic;
    using  System.Text;
    
    
    /// <remarks/>
    // [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.wirelinelogging.module.interdb.lead/xsd")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("WebServiceProxyBuilder", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="LogInfoService", IsNullable=true)]
    public partial class EntityLogInfoService
    {
    }
}
